export const Q = [
	{
		Ques: "Which Is Not a Programming Language ??",
		a: "JAVA",
		b: "RUST",
		c: "CSS",
		d: "GO LANG",
		correct: "c",
	},
	{
		Ques: "Select Odd One Out ??",
		a: "Array",
		b: "stack",
		c: "Tree",
		d: "LinkedList",
		correct: "c",
	},
	{
		Ques: "Father Of Python Language ??",
		a: "Bjarne Stroustrup",
		b: "Rasmus Lerdorf",
		c: "Brendan Eich",
		d: "Guido van Rossum",
		correct: "d",
	},
	{
		Ques: "Which is Not a MarkUp Language ??",
		a: "XML",
		b: "PERL",
		c: "HTML",
		d: "SGML",
		correct: "b",
	},
	{
		Ques: "Old Name of Java is ??",
		a: "Oak",
		b: "palm",
		c: "Ecma",
		d: "Ruby",
		correct: "a",
	},
	{
		Ques: "What is the full form of CSS?",
		a: "Color style sheet",
		b: "Cascading style sheet",
		c: "Concatenated style sheet",
		d: "Creative style sheet",
		correct: "b",
	},
	{
		Ques: "How many heading tags are there in HTML5 ??",
		a: "2",
		b: "6",
		c: "5",
		d: "7",
		correct: "b",
	},
	{
		Ques: "Best Case Complexity of Bubble Sort is ??",
		a: "O(N^2)",
		b: "O(N * Log(N))",
		c: "O(Log (N))",
		d: "O(N)",
		correct: "d",
	},
	{
		Ques: "Which of the following HTML element is used for creating an unordered list?",
		a: "ul",
		b: "ol",
		c: "em",
		d: "td",
		correct: "a",
	},

	{
		Ques: "Rahul's Favourite Language is ",
		a: "Python",
		b: "Java",
		c: "C++",
		d: "Go Lang",
		correct: "b",
	},
];
